# Generated by Django 5.2.7 on 2025-10-30 19:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('stars', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('status', models.CharField(choices=[('viewed', 'Просмотрено'), ('want', 'Хочу посмотреть')], default='want', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
